### ISSUE TITLE
Transactions API: remove base64 encoding 

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#58]
For the get transactions I would suggest we use the same approach weather or not it will end up being base64 encoded or attached files to transmit the data. Currently the API is escaping the XML tags <> as entities (&lt;
…) and it makes it difficult to read and process.

**Comment by stigbd** [comment]
It is difficult to make the xml human-readable. We suggest you use a tool to unescape, e.g. https://www.freeformatter.com/xml-escape.html

**Comment by ekoskent** [comment]
The base64 encoding is not the problem here but rather the fact that the embedded XML (XBRL GL data) for the business transactions was escaped content instead of having XML inside of XML (the other body items) which should be ok. Applying base64 as is done in the voucher APIs would be better or then to have separate attachment files.

**Comment by frodegill** [comment]
Now that GET /transactions/{id} returns an aggregated XBRL GL document, this issue is probably obsolete?
